# name: A workflow for my Hello World file # name of the workflow
# on: push #triggering event for the workflow

jobs:
  build:
    name: Hello world action # Name of the workflow
    runs-on: ubuntu-latest   # Environment for the workflow
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"